### ISSUE TITLE
turnin can use 100% of CPU

### ISSUE THREAD

**Issue by daknob** [zakkak/turnin#27]
It has been observed that the binary `turnin(1)` and more specifically `turnin v2.3.1-2` under unknown conditions consumes 100% of the CPU and the process hangs forever.

**Comment by zakkak** [comment]
Backtraces always help ;)

So it is probably happening due to wrong handling of folders.  Where there any files in the folders you tested with?

**Comment by DaKnOb** [comment]
Some of them were caused by you or people you know better than I do.. ;-) (hy240a)
I don't know but its probably not ```tar(1)``` or has to do with folders.
Why is it a zombie process? Because we ignore all signals (including ```SIGHUP```)? Maybe they're just turnins never completed because the connection was lost or someone killed the parent (```bash(1)```). 
Can you remind me why we ignore ```SIGHUP```s again? :P

**Comment by DaKnOb** [comment]
I have just verified that ```turnin(1)``` indeed does *not* close when I kill ```bash(1)``` (or close the terminal I ssh'd into a remote host) _BUT_ the CPU Usage of the zombie process is 0% since it awaits user input. I killed the parent only in phases where ```turnin(1)``` stops and requires user input (essentially during the ```wanttocontinue()``` function) and in all cases it shows 0% but remains open. 

So there is the possibility that *somehow* the program falls in an infinite loop and the user has no way of closing it and shuts down the terminal OR they all closed the terminal window when it was doing something with forks etc(??!?!?!).

**Comment by zakkak** [comment]
Sounds reasonable... We just inherited the `SIGHUP` ignore behavior it was not one of our decisions.

A self kill command would be nice in general, but the 100% usage is still weird.
_This process will explode in 5 seconds_

**Comment by DaKnOb** [comment]
Maybe check the parent process and if it's dead it should die as well.. Did we really inherit the signal ignorance (sounds funny) or did we add it ourselves to make it even more "secure" since a user cannot easily mess with it? I think it was the second.

**Comment by zakkak** [comment]
Nope, it was there (https://github.com/zakkak/turnin/blob/a1368abea7629c46a1ebb83cd17634cae36d0e3f/turnin.c#L1010) we just moved them at an earlier stage.

**Comment by DaKnOb** [comment]
True.. So something gets in an infinite loop somewhere? I have not been able to reproduce the problem in the testbed.

**Comment by alx01011** [comment]
I launched 3 ssh sessions to the same machine by different users. 

Each user, called `turnin` and waited on the `Do you wan to continue` screen.
After that, I force-terminated each session. 

This is the log for `top -u user` for the first user:
```bash
PID USER      PR  NI    VIRT    RES    SHR S  %CPU  %MEM     TIME+ COMMAND   
725 tester-3  20   0   13716   1568   1336 R 100.0   0.0   0:17.62 turnin 
```
The zombie process kept running even if the user reconnects, the only way to end it, was to call `kill`.

I did a rebuild of `turnin` this time without `SIGHUP` ignore call, and couldn't reproduce.

My guess is that when the `ssh` sessions is terminated, `getchar()` gets the `EOF` signal, and this repeats, I doubt `clearr` is able to clear the `EOF` signal and restore `stdin` in such case.

**Comment by daknob** [comment]
I don't know if this still works, but it seems that many machines are affected to this day:

https://www.csd.uoc.gr/~csd3235/OpenHost/

So perhaps solving this problem will be good for the environment. If only we did it 7 years ago :)

**Comment by alx01011** [comment]
It probably does work. TBH it's pretty easy to cause the bug not surprised many machines run on 40+% cpu.

I have tested @zakkak's solution and it does work, the process terminates after `N` time has passed.

**Comment by daknob** [comment]
Anything that has around 25% / 50% / 75% / 100% CPU is most likely `turnin` (as the computers have 2 cores / 4 threads, and it takes 100% of one). Especially if the utilization is over 5-10'.

Do you think you could see whether checking the parent (and `exit()`ing if it's dead) works? It would probably be cleaner and faster.

**Comment by alx01011** [comment]
> Do you think you could see whether checking the parent (and `exit()`ing if it's dead) works? It would probably be cleaner and faster.

Where should that happen? In the second thread? Something like an infinite loop checking in every iteration? Wouldn't that be expensive?

**Comment by daknob** [comment]
Well, you can only check every second or 5 seconds..

I would assume that if I `ssh` into the computers, and it runs `bash` for me, when my session crashes, `bash` would die, and the check would fail, and then `turnin` would also be calling `exit()`.

**Comment by alx01011** [comment]
> Well, you can only check every second or 5 seconds..
> 
> 
> 
> I would assume that if I `ssh` into the computers, and it runs `bash` for me, when my session crashes, `bash` would die, and the check would fail, and then `turnin` would also be calling `exit()`.

Your assumption is correct. I think this could work. Will test and report back.

**Comment by alx01011** [comment]
So far I have [this](https://github.com/alx01011/turnin/blob/ab47b2601a6886762979ee1bcfa1cf2812808c10/src/turnin.c#L1402), which appears to work fine. I'm not sure if this good or error prone. Waiting for your feedback.

**Comment by zakkak** [comment]
@alx01011 better open a PR so we can discuss the changes there. Thanks!

**Comment by alx01011** [comment]
@zakkak [Check PR#38](https://github.com/zakkak/turnin/pull/38)

**Comment by zakkak** [comment]
> @zakkak Check [PR#38](https://github.com/zakkak/turnin/pull/38)

Hmm that slipped under my radar (missed the email :/ ). Thanks
