### ISSUE TITLE
Potential NULL pointer dereference

### ISSUE THREAD

**Issue by daknob** [zakkak/turnin#41]
In the following part of the code, we get the username that is associated with a particular user ID:

https://github.com/zakkak/turnin/blob/d2b800db86f2ece3d160ea7e9466e52738b79d38/src/turnin.c#L468

The code correctly copies the string to a local variable, as according to the man page, there's no guarantee that this value will continue to live there long term (it's in the static section, and is overwritten by subsequent calls).

However, according to the man page, there's no guarantee that the struct fields that are pointers to `char` arrays will not be `NULL`. Although in practice this always worked, I think it's much safer to introduce a `NULL` check to avoid a dereference.

**Comment by alx01011** [comment]
To be certain, a `NULL` check shall be performed on `pwd->pw_name`?

**Comment by daknob** [comment]
Correct, you cannot dereference `pw_name` like that safely. Since it is needed, aborting with an error is fine.

**Comment by zakkak** [comment]
Closed by #51
