### ISSUE TITLE
Improve error messages

### ISSUE THREAD

**Issue by daknob** [zakkak/turnin#43]
The following line:

https://github.com/zakkak/turnin/blob/d2b800db86f2ece3d160ea7e9466e52738b79d38/src/turnin.c#L235

as well as this:

https://github.com/zakkak/turnin/blob/d2b800db86f2ece3d160ea7e9466e52738b79d38/src/turnin.c#L255

lack the `class` and `user` parts of the error message.

It's a quick PR to add them, and make error reporting better :)

**Comment by alx01011** [comment]
@daknob Is a string format such as `classx: userx: setuid: error` acceptable?

**Comment by daknob** [comment]
I think so. Even `seteuid: class` and `seteuid: user` without any variables are better than this :)

**Comment by zakkak** [comment]
Closed by #51
